apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/seandonmooy-1292/tacticsonline-api
    context: src
    docker:
      dockerfile: api/Dockerfile
    sync:
        infer:
        - 'api/**/*.js'
        - 'lib/**/*.js'
        - '_shared/**/*.js'
  - image: gcr.io/seandonmooy-1292/tacticsonline-gameserver
    context: src
    docker:
      dockerfile: gameserver/Dockerfile
    sync:
        infer:
        - 'gameserver/**/*.js'
        - 'lib/**/*.js'
        - '_shared/**/*.js'
  - image: gcr.io/seandonmooy-1292/tacticsonline-matchmaker
    context: src
    docker:
      dockerfile: matchmaker/Dockerfile
    sync:
        infer:
        - 'matchmaker/**/*.js'
        - 'lib/**/*.js'
        - '_shared/**/*.js'
  - image: gcr.io/seandonmooy-1292/tacticsonline-worker
    context: src
    docker:
      dockerfile: worker/Dockerfile
    sync:
        infer:
        - 'worker/**/*.js'
        - 'lib/**/*.js'
        - '_shared/**/*.js'
  - image: gcr.io/seandonmooy-1292/tacticsonline-www
    context: src
    docker:
      dockerfile: www/Dockerfile
    sync:
        infer:
        - 'www/**/*.js'
        - 'www/**/*.html'
        - 'lib/**/*.js'
deploy:
  kustomize:
    path: "inf/k8s/overlays/dev"
portForward:
- resourceType: deployment
  resourceName: api
  port: 4000
  localPort: 4000
- resourceType: deployment
  resourceName: www
  port: 3000
  localPort: 3000
profiles:
  - name: dev
  - name: prod
    deploy:
      kustomize:
        path: "inf/k8s/overlays/prod"
