apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: api
        logs: json
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
      volumes:
        - name: ssl-volume
          secret:
            secretName: service-cert
      imagePullSecrets:
        - name: registry-secret
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: gcr.io/seandonmooy-1292/tacticsonline-api
          imagePullPolicy: IfNotPresent
          ports:
            - name: https-ports
              containerPort: 4000
            - name: metrics
              containerPort: 5000
          envFrom:
            - secretRef:
                name: common
            - secretRef:
                name: api
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: LOG_LEVEL
              value: info
          volumeMounts:
            - name: ssl-volume
              mountPath: /app/inf/secrets
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1500Mi
