apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  selector:
    matchLabels:
      app: www
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: www
        logs: json
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
      volumes:
        - name: ssl-volume
          secret:
            secretName: service-cert
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: www
          image: gcr.io/seandonmooy-1292/tacticsonline-www
          imagePullPolicy: Always
          ports:
            - name: https-ports
              containerPort: 4000
            - name: metrics
              containerPort: 5000
          volumeMounts:
            - name: ssl-volume
              mountPath: /app/inf/secrets
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1500Mi
          readinessProbe:
            httpGet:
              path: /
              port: https-ports
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: https-ports
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      targetPort: https-ports
  selector:
    app: www
