apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  selector:
    matchLabels:
      app: www
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: www
        logs: json
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
      volumes:
        - name: ssl-volume
          secret:
            secretName: service-cert
      terminationGracePeriodSeconds: 0
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: www
          image: gcr.io/seandonmooy-1292/tacticsonline-www
          imagePullPolicy: IfNotPresent
          ports:
            - name: https-ports
              containerPort: 3000
            - name: metrics
              containerPort: 5000
          envFrom:
            - secretRef:
                name: common
            - secretRef:
                name: www
          volumeMounts:
            - name: ssl-volume
              mountPath: /app/inf/secrets
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1500Mi
